- lib/io/input-clay.js
[Related Trello](https://trello.com/c/Z0tqynOw/36-add-site-to-site-import-in-clay-cli)
Currently, an error is thrown if you attempt to import a published page. This is because clay-cli is currently written with the expectation that all the properties at the root of a page object are URIs or URI arrays. While this is true of draft pages, it is not true of published pages because the publishing process adds non-URI properties. These "page configuration" properties are specified in Amphora [here](https://github.com/clay/amphora/blob/master/lib/services/references.js#L166). This change modifies clay-cli to ignore these properties of the page object (except layout, which _is_ a URI).
> Support import of @published pages

- lib/cmd/import.js
- lib/cmd/touch.js
- lib/io/input-clay.js
- lib/io/input-clay.test.js
- lib/utils/config.test.js
- lib/utils/rest.js
- lib/utils/rest.test.js
Related somewhat to [Trello](https://trello.com/c/Z0tqynOw/36-add-site-to-site-import-in-clay-cli)
We've specified in our listing rules that a function may have no more than four arguments. As of #33, the rest utility breaks this rule. This PR mainly refactors the `get` and `put` fncs to organize all optional arguments under "options" objects and updates tests and dependents to reflect the new signatures.
... also corrects the test name for the config utility from "rest" to "config."
> Refactors rest utility so it doesn't break linting rules

- lib/io/agnostic-chunks.js
Page import gets a page's data and composes each component in that data (via the component's `.json` endpoint). For each component, the import process replaces the prefixes inside its data with the prefix for the target site and then PUTs that data to component's location in the target site.
However, the `replacePrefixes` step is not replacing all prefixes in a composed object because the replacement logic does not recursively apply to all the components within a component's component lists or component properties. As a result, components that are "grandchildren" of page-level components will appear with the _old_ prefixes after import.
This fix ensures the replacement operation applies recursively down a composed component.
> Ensures prefixes are replaced throughout composed component objects

- lib/cmd/config.js
- lib/cmd/export.js
- lib/cmd/import.js
- lib/cmd/lint.js
- lib/cmd/touch.js
- lib/io/agnostic-chunks.js
- lib/io/agnostic-chunks.test.js
- lib/io/input-clay.js
- lib/io/input-clay.test.js
- lib/io/input-files.js
- lib/io/input-files.test.js
- lib/io/output-files.js
- lib/utils/config.js
- lib/utils/config.test.js
- lib/utils/deep-reduce.js
- lib/utils/deep-reduce.test.js
- lib/utils/fetch.js
- lib/utils/logger.js
- lib/utils/normalize-components.js
- lib/utils/normalize-components.test.js
- lib/utils/rest.js
- lib/utils/rest.test.js
- lib/utils/shared-options.js
- lib/utils/urls.js
- lib/utils/urls.test.js
because:
- strict mode helps catch bugs
- consistent semantics (some files were already strict)
- we're stuck on Node 4 in one of our branches and can't use
clay-cli because of `let` not being allowed outside strict mode
in Node 4's V8
> use strict

- package-lock.json
- package.json
`claycli` is not working out-of-the-box via `npm install -g claycli` because `clayutils` is in dev dependencies when it should be in regular dependencies. This PR moves it to regular dependencies.
> Moves clayutils to regular dependencies

- cli/export.js
- cli/lint.js
- lib/cmd/export.js
- lib/cmd/export.test.js
- lib/cmd/import.js
- lib/cmd/import.test.js
- lib/cmd/lint.js
- lib/cmd/lint.test.js
this adds specific error messaging when running claycli commands against urls, when you forget to type in the url (and don't have it set in `CLAYCLI_DEFAULT_URL`)
* import now pipes error and exits early
* export now pipes error and exits early
* lint pipes error
> fix #66, add messaging when running commands against undefined urls

- README.md
let people know that clay outputs logs via `stderr`
> improve dev quality of life by .0001%

- README.md
- lib/cmd/lint.js
- lib/cmd/lint.test.js
- lib/formatting.js
- lib/prefixes.js
- lib/prefixes.test.js
- lib/rest.js
- lib/types.js
- package-lock.json
- package.json
* allows linting components, pages, and public urls by extension
* note: this changes the public url linting to _also_ check the `.html` rendered page
* note: this still checks recursively, so children's templates will also be linted
* note: you may lint against _any_ extension, not just `.html`, e.g. `domain.com/_components/my-cool-feed.rss`
> Lint by extension

- lib/cmd/export.js
- lib/cmd/export.test.js
- lib/cmd/import.js
- lib/cmd/import.test.js
- lib/cmd/lint.js
- lib/cmd/lint.test.js
- lib/formatting.js
- lib/formatting.test.js
- lib/prefixes.js
- lib/prefixes.test.js
- lib/types.js
- package-lock.json
- package.json
* FEATURE: handle `_layouts` in bootstraps and dispatches; importing, linting, and exporting
* FEATURE: handle `meta` in page data and layout instance data, in bootstraps and dispatches
Not sure if this should be considered a breaking change or not, as it does make `meta` a reserved word in page/layout data (currently you can use `meta` as the name of a page area / layout component list if you want, but I don't think any Clay installs actually do)
> _layouts and metadata

- README.md
- lib/cmd/import.js
- lib/cmd/import.test.js
* add `import.parseBootstrap`, to parse bootstraps without doing http calls
* add `import.parseDispatch`, to parse dispatches without doing http calls
* add docs for all available programmatic methods
NOTE: `parseBootstrap` and `parseDispatch` both return streams of _prefixed_ dispatches, e.g.
```
{ 'domain.com/_components/a: { b: 'c' } }
```
These can easily be used by services that have their own connections to your Clay database.
If your bootstrap / dispatch contains errors, they'll be passed through the stream correctly _as errors_. Make sure you [watch for errors](http://highlandjs.org/#errors) or [otherwise handle them](http://highlandjs.org/#stopOnError).
> fix #74, more programmatic api goodness

- lib/cmd/export.js
- lib/cmd/export.test.js
I ran into an issue using the programmatic API attempt to pass the stream from `clayCli.export.fromUrl` into a `clayCli.import` with `{publish: true}` passed as an option.  It was unsuccessful at publishing the page, because the `import` would attempt to PUT to the @published uri of the page before it would PUT the draft versions of the components inside of that page.  Instead, this will export pages AFTER components and layout on the page, instead of before them.
> When exporting, put pages after components and layouts

- README.md
- lib/cmd/import.js
- lib/cmd/import.test.js
- package-lock.json
A function to do the same thing as `parseBootstrap` but doesn't assume Yaml input. The current `parseBootstrap` function doesn't allow for memoization of the yaml parsing which can be CPU intensive, like during amphora startup where the number of parses for NYMag exceeds 8k reads
> Parse Bootstrap JSON

- lib/cmd/import.js
- lib/cmd/import.test.js
* pulls out `import` handling logic to make it more clear
* we handle importing from `stream of strings`, `string`, `object`, and `Buffer` (the last one was causing an issue with v3.4.x)
> fix import by making support more explicit

- lib/cmd/compile/templates.js
- package-lock.json
due to some technical issues with precompilation and `gulp-group-concat`, we didn't launch `clay compile templates` with proper template compilation for components on `npm`. This addresses that.
> enable npm component template precompilation

- lib/cmd/compile/media.js
- lib/cmd/compile/templates.js
- package-lock.json
- package.json
fixes #95, allows `claycli` to be used anywhere (not just in a clay repo). Note that `clay compile` must still be used in a clay repo to compile assets for that repo.
> call amphora-fs in methods

- lib/cmd/compile/scripts.js
- lib/cmd/compile/styles.js
- lib/compilation-helpers.js
This will target all browsers with > 3% global market share, which just so happen to be modern browsers whom'st support es6 syntax and unprefixed css3 rules. Currently (as of Sept 2018) they are:
* android chrome 67
* chrome 67 (+68)
* firefox 61
* ios safari 11.3
Note: we're purposefully excluding UC Browser (a popular chinese browser) because it is a very (_very_) popular malware vector.
> use global > 3% browserslist for autoprefixer and babel

- lib/cmd/compile/styles.js
Allows for interpolation of variables before parsing of nested values.
> Swapping Plugin Ordering

- cli/compile/index.js
- cli/compile/styles.js
- lib/cmd/compile/styles.js
- lib/compilation-helpers.js
- lib/compilation-helpers.test.js
- package-lock.json
The beginnings of a `claycli.config.js` file for compilation config.
Some postCSS plugins require being able to provide arguments to the plugin, like `postcss-functions` for example. This PR adds support for a `claycli.config.js` file which can be expanded up but initially supports passing plugins into PostCSS.
```javascript
'use strict';
module.exports = {
plugins: [
require('postcss-functions')({
functions: {
em: function (pixels, browserContext) {
var browserContext = parseInt(browserContext, 10) || 16,
pixels = parseFloat(pixels);
return pixels / browserContext + 'em';
}
}
})
]
};
```
> Starter Config File

- cli/compile/index.js
- lib/cmd/compile/fonts.js
- lib/cmd/compile/media.js
- lib/cmd/compile/scripts.js
- lib/cmd/compile/styles.js
- lib/cmd/compile/templates.js
Addresses a few issues that were cropping up while using the watch flag for compilation
1. For `styles`, `fonts`, `media`, and `templates` the gulp tasks created for the compile step were not compatible for watch because the underlying highland stream which was returned never actually got consumed (so no work was being done on it)
2. The `media` task was specifying each individual media file in the watch instead of utilizing globs - I believe this was the source of the errors of the type
```(FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)```
as they went away once this was changed
3. The `media` task was two times specified when doing a full compilation, nothing particularly there to fix aside from not being necessary.
4. The …
> Compilation Watch Improvements

- lib/cmd/compile/scripts.js
- lib/cmd/compile/templates.js
Optimizations in the watch for compile command `scripts` and `templates` caused issues where compiled script files would not contain their full context - see https://github.com/clay/claycli/issues/116 for more details.
This PR temporarily removes these optimizations so that watch commands work consistently
- For `scripts` pass all entrypoints through to `buildScripts`
- For `templates` do not exclude unmodified template files when recompiling for template files
> Temporarily Remove Compile Watch Optimizations

- README.md
- cli/compile/custom-tasks.js
- cli/compile/index.js
- index.js
- lib/cmd/compile/custom-tasks.js
- lib/cmd/compile/index.js
#112 
Opening early so we can make sure this matches with what we think will be needed in the future.
- Allows for registering custom tasks in the `claycli.config.js` file
- Command is `clay compile custom-tasks`
- Tasks are run in a `series`, not `parallel` (No real reason, just first pass)
- Logging
- Command name
- Parallel
- Should there be a folder for custom tasks rather than the cli config file or should that be the discretion of the implementation?/
- What args should be passed to the task? Any? The defaults claycli asks for?
Sample pulled from real life gulp task. Args are available via the yargs module in this task, so maybe we don't need to pass anything in.
```javascript
'use strict';
var gulp = require('gulp'),
concat = require('gulp-concat'),
uglify = require('gulp-uglify'), …
```
> Custom Task

- README.md
This PR is tend to fix the `.clayconfig` file example in `README.md`
You can't have whitespace in bash variable assignments as it would be interpreted as a command. I thought this might be misleading as people usually copy/paste examples from readme file.
> removing whitespace from bash example in readme

- .github/main.workflow
- website/siteConfig.js
Add `Algolia` search bar
- Go to the `website` folder
- Install package using `npm install`
- Start your local server using `npm start`
- Go to [localhost](http://localhost:3000/claycli/docs/cli.html)
- Check on the top rigth corner of the page and will be a search input
- Compare with the current [docs page](https://clay.github.io/claycli/docs/cli.html)
https://docusaurus.io/docs/en/search
https://community.algolia.com/docsearch/
Note:
We need the `Angolia` api key to create the secret and the `indexName`
> Add a algolia config and secret

- .github/main.workflow
Update the `main.workflow` file to add a new path for the `Build and deploy` action and a new action to update the version of the docs
- Install [act](https://github.com/nektos/act#installation)
- Go to the [`.github` ](https://github.com/clay/claycli/tree/git_action/.github) folder
- On the `main.workflow` update the[` branch`](https://github.com/clay/claycli/blob/git_action/.github/main.workflow?short_path=8c5ae9c#L7) line to use `branch action_version`
- Use the [`act`](https://github.com/nektos/act#commands) command to simulate a `push` event. The build should be `successful`
- On the `main.workflow` update the[` branch`](https://github.com/clay/claycli/blob/git_action/.github/main.workflow?short_path=8c5ae9c#L7) line to use `branch master`
- Use the …
> Update the main.workflow file to add new action

- docs/cli.md
- docs/issues/compilation_docs.md
- website/sidebars.json
- website/siteConfig.js
Add a folder for the issues that have been answered
Related to the issue https://github.com/clay/claycli/issues/120
- Go to the `website` folder
- Install all dependencies using `npm install`
- Start your local server using `npm run start`
- Test locally at [localhost](http://localhost:3000/claycli/docs/next/issues/compilation_docs)
> Add the issues folder that will document it answer

- website/package.json
- website/siteConfig.js
Update the `gh-pages` manual deploy script and the default option of the project name on the `SiteConfig`
> Update the gh-pages script and update the siteConfig default name

- lib/cmd/config.js
check for a passed in key/url value before defaulting to the env var
> check passed in value for key before defaulting to env var

- lib/cmd/compile/scripts.js
- package-lock.json
- package.json
1. in this repo, on this branch, `npm link`
2. in your sites repo, `npm link claycli`
3. In your sites app folder (wherever your `package.json` file lives), `clay compile scripts` then verify that the file at `app/public/_client-init.js` looks like it has been transpiled - for example the `for...of` loops will be replaced by something like this:
```js
var _iteratorNormalCompletion = true;
var _didIteratorError = false;
var _iteratorError = undefined;
try {
for (var _iterator = instances[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
var el = _step.value;
```
> transpile client-init because it runs on the client in view mode

- lib/cmd/compile/fonts.js
- lib/cmd/compile/styles.js
Setting `CLAYCLI_COMPILE_MINIFED` (or any of the variants) did *not*
minify CSS or Fonts. This was due to our use of a package called
`gulp-if`, which has a usage like this:
```js
gulpIf(condition, trueChild, falseChild, minmatchOptions);
```
Where `condition` is expected to either be:
1. A `boolean`.
2. A `function` that will return a `boolean`.
When setting `CLAYCLI_COMPILE_MINIFIED` from an environment variable we
end up with a `string` value for `minify`, which causes `gulpIf` to
evaluate to `false`, skipping minification.
This commit simply casts `minify` to a `bool` when calling `gulpIf`.
A more robust approach would be to fix typing across the board for
environment variable defaults, providing some sort of `strToBool`
method to cast `['1', 't', 'true', 'y', 'yes']` to `true` and …
> bugfix: enables CSS minification via environment variable

- cli/index.js
Claycli loads requirements for all of its commands even though only one is ever run. compile in particular takes a while to start up, so this PR parses the command line args and calls `require` only on that arg.
New:
```
$ time clay config -k local -r json
{"level":30,"time":1592346996492,"msg":"MadeUpAccessKey","pid":9274,"hostname":"Chase-Felker-MacBook-Pro.local","name":"claycli","claycliVersion":"3.12.1","command":"config","type":"info","_label":"INFO","v":1}
real	0m0.234s
user	0m0.176s
sys	0m0.058s
```
Old:
```
$ time clay config --key stage  --reporter json
{"level":30,"time":1592252061518,"msg":"your-key","pid":78980,"hostname":"Chase-Felker-MacBook-Pro.local","name":"claycli","claycliVersion":"3.12.1","command":"config","type":"info","_label":"INFO","v":1}
real	0m1.716s
user …
```
> import the command you actually use

- .circleci/config.yml
- .circleci/scripts/deploy-docs.sh
- .circleci/scripts/release.sh
- package-lock.json
- package.json
This commit introduces a new release workflow that ensures NPM packages are published in a consistent manner.
The typical workflow will involve creating a release from the **base** branch (currently: `master`).
1. Start by creating a prerelease candidate, selecting the correct version to increment.
```sh
npm run release (prepatch|preminor|premajor)
```
2. This will run `npm version (selection)` and push the branch/tag.
3. CircleCI will publish a package with `--tag=prerelease`, eg. `v8.17.1-0`.
4. When we are ready to promote a release from `prerelease` to `latest` run the following.
```sh
npm run release (patch|minor|major)
```
5. This will run `npm version (selection)` and push the branch/tag.
6. CircleCI will publish a package, eg `v8.17.1`.
---
:warning:
This pull request upgrades …
> Introduces release workflow via CircleCI

- lib/cmd/lint.js
Corresponding fix to https://github.com/clay/clay-kiln/pull/1508 per @james-owen 's suggestion in https://github.com/clay/clay-kiln/pull/1508#discussion_r545388118.
> Allow multiple leading underscores in field names

- cli/pack/options.js
- cli/pack/scripts.js
- lib/cmd/pack/get-webpack-config.js
Previously, we would always build Webpack modules alongside Browserify modules---even in development, where Webpack needs a little more love. This ensures we skip most of the manifest, so Amphora HTML falls back to to our legacy modules automatically.
> Clean up development build patterns.

- lib/cmd/pack/_client-init.js
Due to an improperly anchored regexp, the module initialization script kept trying to pass HTML elements to the exports of arbitrary modules. In the case of the subscription page, for instance, the init script kept passing `div.subscription-multi-step-container` to the default export of `./components/subscription-multi-step-container/services/isValidName.js`. 😶
> Fix bug in component matcher.

- lib/cmd/compile/templates.js
Very small improvement, but it's nice to not have to restart watch if you make a typo in a template.
> catches template compile errors when watching
